apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: warfield-task-manager-prod
resources:
  - auth-migrate-job.yaml
  - task-migrate-job.yaml
images:
  - name: task-manager-auth-service
    newName: "<aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/task-manager-auth-service"
    newTag: "prod"
  - name: task-manager-task-service
    newName: "<aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/task-manager-task-service"
    newTag: "prod"
