apiVersion: v1
kind: Secret
metadata:
  name: task-manager-secrets
  namespace: task-manager
type: Opaque
stringData:
  postgres-password: "0000"
  shared-jwt-signing-key: "shared-microservice-jwt-signing-key-change-me"
  auth-django-secret-key: "auth-service-django-secret-key-change-me"
  task-django-secret-key: "task-service-django-secret-key-change-me"
  calendar-django-secret-key: "calendar-service-django-secret-key-change-me"
  google-client-id: ""
  google-client-secret: ""
  google-calendar-id: "primary"
