apiVersion: v1
kind: ConfigMap
metadata:
  name: task-manager-production-config
  namespace: warfield-task-manager-prod
data:
  DEBUG: "False"
  TIME_ZONE: "Asia/Kolkata"
  USE_PROXY_SSL_HEADER: "True"
  USE_X_FORWARDED_HOST: "True"
  SESSION_COOKIE_SECURE: "True"
  CSRF_COOKIE_SECURE: "True"
  SECURE_SSL_REDIRECT: "False"
  SECURE_HSTS_SECONDS: "31536000"
  SECURE_HSTS_INCLUDE_SUBDOMAINS: "True"
  SECURE_HSTS_PRELOAD: "True"
  JWT_ISSUER: "warfield-task-manager-prod"
  JWT_AUDIENCE: "warfield-task-manager-prod-clients"
  JWT_ACCESS_TOKEN_MINUTES: "60"
  JWT_REFRESH_TOKEN_DAYS: "7"
  GUNICORN_WORKERS: "2"
  GUNICORN_THREADS: "2"
  GUNICORN_TIMEOUT: "60"
  AUTH_POSTGRES_DB: "auth_service"
  TASK_POSTGRES_DB: "task_service"
  CALENDAR_POSTGRES_DB: "calendar_service"
  POSTGRES_USER: "postgres"
  POSTGRES_PORT: "5432"
  FRONTEND_BASE_URL: ""
  TASK_SERVICE_URL: "http://task-service:8000"
  GOOGLE_CALENDAR_REDIRECT_URI: ""
  AUTH_ALLOWED_HOSTS: "auth-service"
  TASK_ALLOWED_HOSTS: "task-service"
  CALENDAR_ALLOWED_HOSTS: "calendar-service"
  AUTH_CSRF_TRUSTED_ORIGINS: ""
  TASK_CSRF_TRUSTED_ORIGINS: ""
  CALENDAR_CSRF_TRUSTED_ORIGINS: ""
