apiVersion: v1
kind: Secret
metadata:
  name: task-manager-production-secrets
  namespace: warfield-task-manager-prod
type: Opaque
stringData:
  postgres-password: "vN7mQ2zR8kP4Task2026"
  auth-database-url: "postgresql://postgres:vN7mQ2zR8kP4Task2026@auth-db:5432/auth_service"
  task-database-url: "postgresql://postgres:vN7mQ2zR8kP4Task2026@task-db:5432/task_service"
  calendar-database-url: "postgresql://postgres:vN7mQ2zR8kP4Task2026@calendar-db:5432/calendar_service"
  shared-jwt-signing-key: "0oP1!vR7#kX2@jM5$sQ9^nH4&dL8*wC3"
  auth-django-secret-key: "django-auth-6b2f1f84-0d54-4e2e-98f3-5f99a1e1f012"
  task-django-secret-key: "django-task-5210e157-b0f5-421f-a887-bf1a2832630c"
  calendar-django-secret-key: "django-calendar-8e7be0f9-464b-4bda-99d4-a30d984c9fd7"
  google-client-id: ""
  google-client-secret: ""
  google-calendar-id: "primary"
